palette = "Bunny"

format = """
$directory\ 
$character\
"""
right_format = """
$git_branch\
"""
add_newline = false

# Language modules disabled
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[username]
show_always = true
style_user = "fg:accent bold"
style_root = "fg:accent bold"
format = '[$user]($style)'
disabled = false

[conda]
format = ' [$symbol$environment](dimmed green) '

[character]
success_symbol = "[ ğŸ‡](green bold)"
error_symbol = "[ ğŸ‡](rose)"
vicmd_symbol = "[ ğŸ‡](lavender)"

[directory]
format = "[ î—¿ ](fg:accent)[$path](fg:accent bold)"
style = "fg:muted_dark"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[[î¬§ ](fg:accent bold)$branch](fg:accent bold)"
style = "fg:base"

[git_status]
format = "[$all_status$ahead_behind](fg:accent_dark) "
style = "fg:base"
conflicted = "="
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "ï˜«"
untracked = "?${count}"
stashed = "ï£•"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "ï™•${count}"


[palettes.Bunny]
background = "#17131A"
background_soft = "#221B26"
lighter_background = "#312936"
purple_foreground = "#D6C1ED"
green_foreground = "#D9E8CD"
grey_foreground = "#A89DB2"
accent = "#9A5EE0"
accent_dark = "#6E3FCF"
accent_soft = "#B18EDC"
additional_accent = "#C48FB3"
additional_accent_dark = "#A56C8A"
complementary = "#7CA53D"
complementary_soft = "#A4CE70"
border_grey = "#4B4354"
